-- 031_day_audits.sql
--
-- One audit per publication day: every article of the day nested under the
-- brief link it answers to, with score and disposition — the document the
-- client kept asking for by hand, generated by the pipeline instead.
--
-- Written by the News Quality passes and finalised by the 23:00 run, the one
-- that closes the day. The morning email and the Teams card read the tally for
-- the day they cover; the dashboard renders the stored HTML.
CREATE TABLE IF NOT EXISTS day_audits (
  day        date PRIMARY KEY,
  tally      jsonb NOT NULL,        -- {fetched, sent, queued, held, excluded}
  html       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
