'use client';

import { useEffect, useState } from 'react';

/**
 * The daily fetch-audit PDF, in a floating window.
 *
 * One report per publication day, generated by the 05:00 workflow beside the
 * send it verifies and stored as bytes — this window only ever shows the
 * stored artefact, because a verification report that re-renders from moved
 * data verifies nothing. Days come from the store; the browser renders the
 * PDF inline and its own toolbar saves it.
 */
export function SourceReportButton() {
  const [open, setOpen] = useState(false);
  const [days, setDays] = useState<{ day: string; has_pdf: boolean }[] | null>(null);
  const [sel, setSel] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = async () => {
    setOpen(true);
    setError(null);
    try {
      const r = await fetch('/api/source-report?list=1', { cache: 'no-store' });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const j = await r.json();
      setDays(j.days);
      if (j.days.length) setSel(j.days[0].day);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setOpen(false);
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  return (
    <>
      <button
        onClick={load}
        className="rounded-md border border-ink-700 px-3 py-1.5 text-sm text-ink-200
                   transition hover:border-brief-a hover:text-brief-a"
      >
        Fetch audit (PDF) ↗
      </button>

      {open && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"
          onClick={() => setOpen(false)}
        >
          <div
            className="flex h-full max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl border border-ink-700 bg-ink-900"
            onClick={e => e.stopPropagation()}
          >
            <header className="flex flex-wrap items-center justify-between gap-3 border-b border-ink-800 px-5 py-3">
              <div>
                <p className="text-[11px] uppercase tracking-[0.14em] text-ink-400">
                  Daily fetch audit — stored each 05:00
                </p>
                <p className="text-sm font-semibold text-ink-100">
                  {sel ? `Publication day ${sel}` : 'Source verification reports'}
                </p>
              </div>
              <div className="flex items-center gap-2">
                {sel && (
                  <a
                    href={`/api/source-report?date=${sel}`}
                    download={`BEXT-Fetch-Audit-pubday-${sel}.pdf`}
                    className="rounded-md border border-brief-a/40 bg-brief-a/10 px-3 py-1 text-xs
                               font-medium text-brief-a hover:bg-brief-a/20"
                  >
                    Download
                  </a>
                )}
                <button
                  onClick={() => setOpen(false)}
                  className="rounded-lg border border-ink-700 px-3 py-1 text-xs text-ink-300 hover:text-ink-100"
                >
                  Close (Esc)
                </button>
              </div>
            </header>

            <div className="flex flex-wrap gap-1.5 border-b border-ink-800 px-5 py-2">
              {days === null && !error && <span className="text-xs text-ink-500">loading…</span>}
              {days?.length === 0 && (
                <span className="text-xs text-ink-400">
                  No reports stored yet — the first generates with tomorrow&rsquo;s 05:00 send.
                </span>
              )}
              {days?.map(d => (
                <button
                  key={d.day}
                  onClick={() => setSel(d.day)}
                  className={`rounded-full border px-2.5 py-0.5 text-xs ${
                    sel === d.day
                      ? 'border-brief-a bg-brief-a/10 text-brief-a'
                      : 'border-ink-700 text-ink-300 hover:border-ink-500'
                  }`}
                >
                  {d.day}{!d.has_pdf && ' (html)'}
                </button>
              ))}
            </div>

            <div className="flex-1 overflow-hidden bg-white">
              {error ? (
                <p className="p-6 text-sm text-blocked">{error}</p>
              ) : sel ? (
                <iframe
                  title={`Fetch audit ${sel}`}
                  src={`/api/source-report?date=${sel}`}
                  className="h-full w-full border-0"
                />
              ) : null}
            </div>
          </div>
        </div>
      )}
    </>
  );
}
