/**
 * AUTO-GENERATED by n8n/build-architecture.js
 * DO NOT EDIT DIRECTLY. Run `node n8n/build-architecture.js` to regenerate.
 * Preflight check R033 verifies this file matches the exported workflows.
 */

export type ArchitectureDomain = 'brief_a' | 'brief_b' | 'content' | 'ops' | 'cross_domain';
export type ActorType = 'ai' | 'you' | 'system';

export interface ArchitectureNode {
  id: string;
  name: string;
  type: string;
  actor: ActorType;
  reads: string[];
  writes: string[];
  alwaysOutputData?: boolean;
}

export interface ArchitectureWorkflow {
  slug: string;
  name: string;
  domain: ArchitectureDomain;
  trigger: {
    type: string;
    label: string;
  };
  tablesRead: string[];
  tablesWritten: string[];
  nodes: ArchitectureNode[];
}

export interface ArchitectureEdge {
  from: string;
  to: string;
  table: string;
  domain: ArchitectureDomain;
}

export interface ArchitectureGraph {
  generatedAt: string;
  workflowCount: number;
  edgeCount: number;
  workflows: ArchitectureWorkflow[];
  edges: ArchitectureEdge[];
}

export const ARCHITECTURE_GRAPH: ArchitectureGraph = {
  "generatedAt": "2026-08-31T02:42:40.053Z",
  "workflowCount": 15,
  "edgeCount": 53,
  "workflows": [
    {
      "slug": "BEXT-Article-Analysis",
      "name": "BEXT — Article Analysis",
      "domain": "brief_a",
      "trigger": {
        "type": "schedule",
        "label": "Interval (30m)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "sources"
      ],
      "tablesWritten": [
        "article_analysis"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Every 30 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "load",
          "name": "Load unanalysed",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "analyse",
          "name": "Score with Gemini",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "save",
          "name": "Save analysis",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "article_analysis"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Content-Actions",
      "name": "BEXT — Content Actions",
      "domain": "content",
      "trigger": {
        "type": "webhook",
        "label": "Webhook (/webhook/content-actions)"
      },
      "tablesRead": [],
      "tablesWritten": [],
      "nodes": [
        {
          "id": "hook",
          "name": "Action request",
          "type": "n8n-nodes-base.webhook",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "route",
          "name": "Route action",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "apply",
          "name": "Apply",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        }
      ]
    },
    {
      "slug": "BEXT-Content-Drafts",
      "name": "BEXT — Content Drafts",
      "domain": "content",
      "trigger": {
        "type": "webhook",
        "label": "Webhook (/webhook/content-drafts)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "content_topics"
      ],
      "tablesWritten": [],
      "nodes": [
        {
          "id": "hook",
          "name": "Draft request",
          "type": "n8n-nodes-base.webhook",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "claim",
          "name": "Claim a selection",
          "type": "n8n-nodes-base.postgres",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "context",
          "name": "Load topic and voice",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "content_topics"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "sources",
          "name": "Load the sources",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "content_topics"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "assemble",
          "name": "Assemble context",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "draft",
          "name": "Write two variants",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "save",
          "name": "Save drafts",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "poll",
          "name": "Every 3 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Content-Topics",
      "name": "BEXT — Content Topics",
      "domain": "content",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (10 6 * * 1)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "report_items",
        "sources"
      ],
      "tablesWritten": [
        "content_topics"
      ],
      "nodes": [
        {
          "id": "fortnightly",
          "name": "Fortnightly",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "open",
          "name": "Open a cycle",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "claim",
          "name": "Claim a cycle",
          "type": "n8n-nodes-base.postgres",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "load",
          "name": "Load the window",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "report_items",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "shape",
          "name": "Carry the cycle",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "rank",
          "name": "Rank three topics",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "save",
          "name": "Save topics",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "content_topics"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "hook",
          "name": "Cycle request",
          "type": "n8n-nodes-base.webhook",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "poll",
          "name": "Every 3 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Contract-Test",
      "name": "BEXT — Contract Test",
      "domain": "ops",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (0 2 * * *)"
      },
      "tablesRead": [],
      "tablesWritten": [
        "integration_health"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Daily 02:00 AEST",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "assert",
          "name": "Assert contracts",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record result",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "integration_health"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Daily-News-Card",
      "name": "BEXT — Daily News Card",
      "domain": "brief_a",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (20 5 * * *)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "report_items",
        "reports",
        "sources"
      ],
      "tablesWritten": [
        "integration_health",
        "reports"
      ],
      "nodes": [
        {
          "id": "cron",
          "name": "Daily 05:20 AEST",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "load",
          "name": "Load the day",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "report_items",
            "reports",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "render",
          "name": "Build card and list",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "store",
          "name": "Store fetch list",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "reports"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "post",
          "name": "Post to Teams",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record result",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "integration_health"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Daily-Report",
      "name": "BEXT — Daily Report",
      "domain": "brief_a",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (0 5 * * *)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "report_items",
        "reports",
        "sources"
      ],
      "tablesWritten": [
        "articles",
        "integration_health",
        "report_items",
        "reports"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Daily 05:00 AEST",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "pull",
          "name": "Top articles, prior day",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "report_items",
            "reports",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "brief",
          "name": "Hermes writes the brief",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "deliv",
          "name": "Check deliverability",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "images",
          "name": "Fetch article images",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "saveimages",
          "name": "Save article images",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "articles"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "render",
          "name": "Render HTML",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "save",
          "name": "Save report",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "reports"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "items",
          "name": "Record items sent",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "reports"
          ],
          "writes": [
            "report_items"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "send",
          "name": "Send via Graph",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "mark",
          "name": "Mark sent",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "reports"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "health",
          "name": "Record result",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "integration_health"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Graph-Health",
      "name": "BEXT — Graph Health",
      "domain": "ops",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (0 6 * * *)"
      },
      "tablesRead": [
        "meeting_minutes"
      ],
      "tablesWritten": [
        "integration_health"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Daily 06:00",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "seen",
          "name": "Load minuted transcripts",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "meeting_minutes"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "check",
          "name": "Check Graph",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record health",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "integration_health"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "gate",
          "name": "Only when broken",
          "type": "n8n-nodes-base.if",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "alert",
          "name": "Alert by email",
          "type": "n8n-nodes-base.emailSend",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-LinkedIn-Publish",
      "name": "BEXT — LinkedIn Publish",
      "domain": "content",
      "trigger": {
        "type": "schedule",
        "label": "Interval (15m)"
      },
      "tablesRead": [],
      "tablesWritten": [],
      "nodes": [
        {
          "id": "trigger",
          "name": "Every 15 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "due",
          "name": "Due posts",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "publish",
          "name": "Publish or prepare",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record result",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "notify",
          "name": "Notify Teams",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Meeting-Intake",
      "name": "BEXT — Meeting Intake",
      "domain": "brief_b",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (*/15 * * * *)"
      },
      "tablesRead": [
        "meeting_minutes"
      ],
      "tablesWritten": [
        "meeting_minutes"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Every 15 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "seen",
          "name": "Load processed meetings",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "meeting_minutes"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "process",
          "name": "Transcribe and draft",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record minutes",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "meeting_minutes"
          ],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-News-Quality",
      "name": "BEXT — News Quality",
      "domain": "ops",
      "trigger": {
        "type": "schedule",
        "label": "Schedule (0 6 * * *)"
      },
      "tablesRead": [
        "article_analysis",
        "articles",
        "incidents",
        "report_items",
        "reports",
        "sources"
      ],
      "tablesWritten": [
        "article_analysis",
        "articles",
        "incidents",
        "integration_health"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Three times daily AEST",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "load",
          "name": "Articles missing a date",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "enrich",
          "name": "Read publish dates",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "save",
          "name": "Save publish dates",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "report_items",
            "reports"
          ],
          "writes": [
            "articles"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "rescore",
          "name": "Requeue rescored articles",
          "type": "n8n-nodes-base.postgres",
          "actor": "ai",
          "reads": [
            "article_analysis"
          ],
          "writes": [
            "article_analysis"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "loadkind",
          "name": "Undated pages to judge",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "articles",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "judge",
          "name": "News or reference",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "savekind",
          "name": "Save the verdict",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "articles"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "coverage",
          "name": "Record coverage",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "articles",
            "sources"
          ],
          "writes": [
            "integration_health"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "quiet",
          "name": "Quiet sources",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "articles",
            "incidents",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "doctor",
          "name": "Diagnose quiet sources",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "incid",
          "name": "Record incidents",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "incidents"
          ],
          "writes": [
            "incidents"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "page",
          "name": "Page Teams",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "audload",
          "name": "Load audit data",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "article_analysis",
            "articles",
            "report_items",
            "reports",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "audbuild",
          "name": "Build day audit",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "audsave",
          "name": "Save day audit",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Newsletter-Intake",
      "name": "BEXT — Newsletter Intake",
      "domain": "brief_a",
      "trigger": {
        "type": "imap",
        "label": "IMAP (Email Intake)"
      },
      "tablesRead": [
        "sources"
      ],
      "tablesWritten": [
        "articles",
        "newsletter_messages"
      ],
      "nodes": [
        {
          "id": "imap",
          "name": "Watch the mailbox",
          "type": "n8n-nodes-base.emailReadImap",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "classify",
          "name": "Read the newsletter",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "insert",
          "name": "Insert articles",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "sources"
          ],
          "writes": [
            "articles"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "seen",
          "name": "Record the message",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "newsletter_messages"
          ],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Self-Heal",
      "name": "BEXT — Self Heal",
      "domain": "ops",
      "trigger": {
        "type": "schedule",
        "label": "Interval (15m)"
      },
      "tablesRead": [
        "incidents"
      ],
      "tablesWritten": [
        "incidents"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Every 15 minutes",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "pending",
          "name": "Load unvalidated",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "incidents"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "heal",
          "name": "Classify, heal and validate",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "record",
          "name": "Record incidents",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "incidents"
          ],
          "writes": [
            "incidents"
          ],
          "alwaysOutputData": true
        },
        {
          "id": "escalate",
          "name": "Escalate to Teams",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Source-Ingest",
      "name": "BEXT — Source Ingest",
      "domain": "brief_a",
      "trigger": {
        "type": "schedule",
        "label": "Hourly (1h)"
      },
      "tablesRead": [
        "articles",
        "newsletter_messages",
        "sources"
      ],
      "tablesWritten": [
        "articles",
        "sources"
      ],
      "nodes": [
        {
          "id": "trigger",
          "name": "Every hour",
          "type": "n8n-nodes-base.scheduleTrigger",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "load",
          "name": "Load active sources",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [
            "articles",
            "newsletter_messages",
            "sources"
          ],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "fetch",
          "name": "Fetch and parse",
          "type": "n8n-nodes-base.code",
          "actor": "ai",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "split",
          "name": "Collect articles",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "statuses",
          "name": "Collect statuses",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "insert",
          "name": "Insert articles",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "articles"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "health",
          "name": "Record source health",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [
            "sources"
          ],
          "alwaysOutputData": false
        },
        {
          "id": "attempts",
          "name": "Record fetch attempts",
          "type": "n8n-nodes-base.postgres",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": true
        },
        {
          "id": "kuma",
          "name": "Heartbeat",
          "type": "n8n-nodes-base.httpRequest",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    },
    {
      "slug": "BEXT-Teams-Inbound",
      "name": "BEXT — Teams Inbound",
      "domain": "brief_b",
      "trigger": {
        "type": "webhook",
        "label": "Webhook (/webhook/teams-inbound)"
      },
      "tablesRead": [],
      "tablesWritten": [],
      "nodes": [
        {
          "id": "hook",
          "name": "Teams inbound",
          "type": "n8n-nodes-base.webhook",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "normalise",
          "name": "Normalise payload",
          "type": "n8n-nodes-base.code",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "gate",
          "name": "Only transcripts",
          "type": "n8n-nodes-base.if",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        },
        {
          "id": "run",
          "name": "Run Meeting Intake",
          "type": "n8n-nodes-base.executeWorkflow",
          "actor": "system",
          "reads": [],
          "writes": [],
          "alwaysOutputData": false
        }
      ]
    }
  ],
  "edges": [
    {
      "from": "BEXT-Article-Analysis",
      "to": "BEXT-Content-Drafts",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Article-Analysis",
      "to": "BEXT-Content-Topics",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Article-Analysis",
      "to": "BEXT-Daily-News-Card",
      "table": "article_analysis",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Article-Analysis",
      "to": "BEXT-Daily-Report",
      "table": "article_analysis",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Article-Analysis",
      "to": "BEXT-News-Quality",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Content-Topics",
      "to": "BEXT-Content-Drafts",
      "table": "content_topics",
      "domain": "content"
    },
    {
      "from": "BEXT-Daily-News-Card",
      "to": "BEXT-Daily-Report",
      "table": "reports",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Daily-News-Card",
      "to": "BEXT-News-Quality",
      "table": "reports",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Article-Analysis",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Content-Drafts",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Content-Topics",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Content-Topics",
      "table": "report_items",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Daily-News-Card",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Daily-News-Card",
      "table": "report_items",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Daily-News-Card",
      "table": "reports",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-News-Quality",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-News-Quality",
      "table": "report_items",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-News-Quality",
      "table": "reports",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Daily-Report",
      "to": "BEXT-Source-Ingest",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Meeting-Intake",
      "to": "BEXT-Graph-Health",
      "table": "meeting_minutes",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Article-Analysis",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Article-Analysis",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Content-Drafts",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Content-Drafts",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Content-Topics",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Content-Topics",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Daily-News-Card",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Daily-News-Card",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Daily-Report",
      "table": "article_analysis",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Daily-Report",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Self-Heal",
      "table": "incidents",
      "domain": "ops"
    },
    {
      "from": "BEXT-News-Quality",
      "to": "BEXT-Source-Ingest",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Article-Analysis",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Content-Drafts",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Content-Topics",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Daily-News-Card",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Daily-Report",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-News-Quality",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Source-Ingest",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Newsletter-Intake",
      "to": "BEXT-Source-Ingest",
      "table": "newsletter_messages",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Self-Heal",
      "to": "BEXT-News-Quality",
      "table": "incidents",
      "domain": "ops"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Article-Analysis",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Article-Analysis",
      "table": "sources",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Content-Drafts",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Content-Topics",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Content-Topics",
      "table": "sources",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Daily-News-Card",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Daily-News-Card",
      "table": "sources",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Daily-Report",
      "table": "articles",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Daily-Report",
      "table": "sources",
      "domain": "brief_a"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-News-Quality",
      "table": "articles",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-News-Quality",
      "table": "sources",
      "domain": "cross_domain"
    },
    {
      "from": "BEXT-Source-Ingest",
      "to": "BEXT-Newsletter-Intake",
      "table": "sources",
      "domain": "brief_a"
    }
  ]
};
